package vest.ancestry;

import lombok.Getter;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.text.WordUtils;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import static vest.Constants.*;

@Getter
public enum Heritage {
    ANCIENT_BLOODED(DWARF_NAME),
    ANVIL(DWARF_NAME),
    DEATH_WARDEN(DWARF_NAME),
    ELEMENTAL_HEART(DWARF_NAME),
    FORGE(DWARF_NAME),
    OATHKEEPER(DWARF_NAME),
    ROCK(DWARF_NAME),
    STRONG_BLOODED(DWARF_NAME),
    ANCIENT(ELF_NAME),
    ARCTIC(ELF_NAME),
    CAVERN_ELF(ELF_NAME),
    DESERT(ELF_NAME),
    SEER(ELF_NAME),
    WHISPER(ELF_NAME),
    WOODLAND(ELF_NAME),
    CHAMELEON(GNOME_NAME),
    FEY_TOUCHED(GNOME_NAME),
    SENSATE(GNOME_NAME),
    UMBRAL(GNOME_NAME),
    VIVACIOUS(GNOME_NAME),
    WELLSPRING(GNOME_NAME),
    CHARHIDE(GOBLIN_NAME),
    IRONGUT(GOBLIN_NAME),
    RAZORTOOTH(GOBLIN_NAME),
    SNOW(GOBLIN_NAME),
    TAILED(GOBLIN_NAME),
    TREEDWELLER(GOBLIN_NAME),
    UNBREAKABLE(GOBLIN_NAME),
    GUTSY(HALFLING_NAME),
    HILLOCK(HALFLING_NAME),
    NOMADIC(HALFLING_NAME),
    OBSERVANT(HALFLING_NAME),
    TWILIGHT(HALFLING_NAME),
    WILDWOOD(HALFLING_NAME),
    HALF_ELF(HUMAN_NAME),
    HALF_ORC(HUMAN_NAME),
    SKILLED(HUMAN_NAME),
    VERSATILE(HUMAN_NAME),
    WINTERTOUCHED(HUMAN_NAME),
    ELFBANE(HOBGOBLIN_NAME),
    RUNTBOSS(HOBGOBLIN_NAME),
    SMOKEWORKER(HOBGOBLIN_NAME),
    WARMARCH(HOBGOBLIN_NAME),
    WARRENBRED(HOBGOBLIN_NAME),
    FUNGUS(LESHY_NAME),
    GOURD(LESHY_NAME),
    LEAF(LESHY_NAME),
    VINE(LESHY_NAME),
    CLIFFSCALE(LIZARDFOLK_NAME),
    FRILLED(LIZARDFOLK_NAME),
    SANDSTRIDER(LIZARDFOLK_NAME),
    UNSEEN(LIZARDFOLK_NAME),
    WETLANDER(LIZARDFOLK_NAME),
    BLOODHOUND(SHOONY_NAME),
    FISHSEEKER(SHOONY_NAME),
    PADDLER(SHOONY_NAME),
    THICKCOAT(SHOONY_NAME),
    JUNGLE(CATFOLK_NAME),
    NINE_LIVES(CATFOLK_NAME),
    WINTER(CATFOLK_NAME),
    HUNTING(CATFOLK_NAME),
    CLAWS(CATFOLK_NAME),
    CAVERN_KOBOLD(KOBOLD_NAME),
    DRAGONSCALED(KOBOLD_NAME),
    SPELLSCALED(KOBOLD_NAME),
    STRONGJAW(KOBOLD_NAME),
    VENOMTAIL(KOBOLD_NAME),
    BADLANDS(ORC_NAME),
    DEEP(ORC_NAME),
    HOLD_SCARRED(ORC_NAME),
    RAINFALL(ORC_NAME),
    DEEP_RAT(RATFOLK_NAME),
    DESERT_RAT(RATFOLK_NAME),
    LONGSNOUT(RATFOLK_NAME),
    SEWER(RATFOLK_NAME),
    SHADOW(RATFOLK_NAME),
    JINXED(TENGU_NAME),
    MOUNTAINKEEPER(TENGU_NAME),
    SKYBORN(TENGU_NAME),
    STORMTOSSED(TENGU_NAME),
    TALONED(TENGU_NAME);

    private final String ancestry;

    Heritage(String ancestry) {
        this.ancestry = ancestry;
    }

    public static List<Heritage> getHeritagesByAncestry(String ancestry) {
        return Arrays.stream(values())
                .filter(h -> StringUtils.equalsIgnoreCase(h.ancestry, ancestry))
                .collect(Collectors.toList());
    }

    public String getDisplayName() {
        return WordUtils.capitalize(name().toLowerCase().replaceAll("_", " "));
    }
}
